<?php

namespace ContainerTm8xdMg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LauaVgaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LauaVga' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LauaVga'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\DefaultController::delete' => ['privates', '.service_locator.LG7ntvO', 'get_ServiceLocator_LG7ntvOService', true],
            'App\\Controller\\DefaultController::edit' => ['privates', '.service_locator.LG7ntvO', 'get_ServiceLocator_LG7ntvOService', true],
            'App\\Controller\\DefaultController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\DefaultController::show' => ['privates', '.service_locator.KJSb96P', 'get_ServiceLocator_KJSb96PService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\DefaultController:delete' => ['privates', '.service_locator.LG7ntvO', 'get_ServiceLocator_LG7ntvOService', true],
            'App\\Controller\\DefaultController:edit' => ['privates', '.service_locator.LG7ntvO', 'get_ServiceLocator_LG7ntvOService', true],
            'App\\Controller\\DefaultController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\DefaultController:show' => ['privates', '.service_locator.KJSb96P', 'get_ServiceLocator_KJSb96PService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\DefaultController::delete' => '?',
            'App\\Controller\\DefaultController::edit' => '?',
            'App\\Controller\\DefaultController::new' => '?',
            'App\\Controller\\DefaultController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\DefaultController:delete' => '?',
            'App\\Controller\\DefaultController:edit' => '?',
            'App\\Controller\\DefaultController:new' => '?',
            'App\\Controller\\DefaultController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
