<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTm8xdMg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTm8xdMg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTm8xdMg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTm8xdMg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTm8xdMg\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tm8xdMg',
    'container.build_id' => '9c0aa805',
    'container.build_time' => 1727700365,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTm8xdMg');
