<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_font' => [['fontName'], ['_controller' => 'web_profiler.controller.profiler::fontAction'], [], [['text', '.woff2'], ['variable', '/', '[^/\\.]++', 'fontName', true], ['text', '/_profiler/font']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_book_new' => [[], ['_controller' => 'App\\Controller\\DefaultController::new'], [], [['text', '/new']], [], [], []],
    'app_book_show' => [['id'], ['_controller' => 'App\\Controller\\DefaultController::show'], [], [['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'app_book_edit' => [['id'], ['_controller' => 'App\\Controller\\DefaultController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'app_book_delete' => [['id'], ['_controller' => 'App\\Controller\\DefaultController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'app_welcome_index_gender' => [['name', 'gender'], ['gender' => 'h', '_controller' => 'App\\Controller\\WelcomeController::indexCustom'], ['gender' => 'h|f'], [['variable', '/', 'h|f', 'gender', true], ['variable', '/', '[^/]++', 'name', true], ['text', '/welcome']], [], [], []],
    'app_welcome_index_basic' => [['name'], ['_controller' => 'App\\Controller\\WelcomeController::indexBasic'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/welcome']], [], [], []],
    'App\Controller\DefaultController::new' => [[], ['_controller' => 'App\\Controller\\DefaultController::new'], [], [['text', '/new']], [], [], []],
    'App\Controller\DefaultController::show' => [['id'], ['_controller' => 'App\\Controller\\DefaultController::show'], [], [['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'App\Controller\DefaultController::edit' => [['id'], ['_controller' => 'App\\Controller\\DefaultController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'App\Controller\DefaultController::delete' => [['id'], ['_controller' => 'App\\Controller\\DefaultController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true]], [], [], []],
    'App\Controller\WelcomeController::indexCustom' => [['name', 'gender'], ['gender' => 'h', '_controller' => 'App\\Controller\\WelcomeController::indexCustom'], ['gender' => 'h|f'], [['variable', '/', 'h|f', 'gender', true], ['variable', '/', '[^/]++', 'name', true], ['text', '/welcome']], [], [], []],
    'App\Controller\WelcomeController::indexBasic' => [['name'], ['_controller' => 'App\\Controller\\WelcomeController::indexBasic'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/welcome']], [], [], []],
];
